// Generated by CoffeeScript 1.8.0
(function() {
  var Mollie, mollie;

  Mollie = require("../lib/mollie");


  /*
  	Initialize the Mollie API library with your API key.
  	See: https://www.mollie.com/beheer/account/profielen/
   */

  mollie = new Mollie.API.Client();

  mollie.setApiKey("test_V6Qxi9pKA3PrdDcBpyCDnRWYbtBJpG");

  mollie.setApiEndpoint("https://api.mollie.dev");

  module.exports = mollie;

}).call(this);
